### ISSUE TITLE
Description should be a multi-line field

### ISSUE THREAD

**Issue by schlomo** [alihuber/icalendar_creator#1]
I would like to have a description that contains more than one line, could you turn the input field into a textarea to allow multi-line input?

**Comment by alihuber** [comment]
I published an update that turns description into a text field input. Unfortunately I completely lost track with this project and stopped to maintain it years ago, so I have no clue what line breaks in the description will do to the generated file. Please let me know if this causes any problems, thanks.

**Comment by schlomo** [comment]
Looks good to me, thanks a lot.

❤️ 

BTW, long lines of description should be folded: https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html

I hope that all modern clients can also handle unfolded long lines...
